import UploadFile from './uploadFile';

const columns = [
  { name: 'Transaction Date & Time', uid: 'transactionDateTime' },
  { name: 'Patient Id', uid: 'patientId' },
  { name: 'Transaction Id', uid: 'transactionId' },
  { name: 'Services', uid: 'service', sortable: true },
  { name: 'Department', uid: 'department', sortable: true },
  { name: 'Total Amount', uid: 'totalAmount' },
  { name: 'GST Amount', uid: 'gstAmount' },
  { name: 'Payment Type', uid: 'paymentType', sortable: true },
  { name: 'Invoice Type', uid: 'invoice' },
  { name: 'Upload', uid: 'upload' },
  { name: 'Actions', uid: 'actions' },
];

const paymentTypeOptions = [
  { name: 'Card', uid: 'Card' },
  { name: 'Cash', uid: 'Cash' },
  { name: 'Online', uid: 'Online' },
];

const users = [
  {
    transactionDateTime: '14 May 2024 & 3:25pm',
    patientId: '12345',
    transactionId: 'xxx12345',
    service: 'Medication',
    department: 'Operation',
    totalAmount: '120000',
    gstAmount: '1200',
    paymentType: 'Card',
    invoice: 'Tax Invoice',
  },
  {
    transactionDateTime: '14 May 2024 & 3:26pm',
    patientId: '12346',
    transactionId: 'xxx12345',
    service: 'Medication',
    department: 'LabTest',
    totalAmount: '120000',
    gstAmount: '1200',
    paymentType: 'Card',
    invoice: 'Tax Invoice',
  },
  {
    transactionDateTime: '14 May 2024 & 3:27pm',
    patientId: '12347',
    transactionId: 'xxx12345',
    service: 'LabTest',
    department: 'LabTest',
    totalAmount: '120000',
    gstAmount: '1200',
    paymentType: 'Cash',
    invoice: 'Tax Invoice',
  },
  {
    transactionDateTime: '14 May 2024 & 3:28pm',
    patientId: '12348',
    transactionId: 'xxx12345',
    service: 'Operation',
    department: 'LabTest',
    totalAmount: '120000',
    gstAmount: '1200',
    paymentType: 'Online',
    invoice: 'Tax Invoice',
    // upload: <UploadFile />,
  },
  {
    transactionDateTime: '14 May 2024 & 3:29pm',
    patientId: '12349',
    transactionId: 'xxx12345',
    service: 'LabTest',
    department: 'LabTest',
    totalAmount: '120000',
    gstAmount: '1200',
    paymentType: 'Cash',
    invoice: 'Tax Invoice',
  },
  {
    transactionDateTime: '14 May 2024 & 3:30pm',
    patientId: '12350',
    transactionId: 'xxx12345',
    service: 'Medication',
    totalAmount: '120000',
    gstAmount: '1200',
    paymentType: 'Card',
    invoice: 'Tax Invoice',
  },
  {
    transactionDateTime: '14 May 2024 & 3:31pm',
    patientId: '12351',
    transactionId: 'xxx12345',
    service: 'Medication',
    totalAmount: '120000',
    gstAmount: '1200',
    paymentType: 'Online',
    invoice: 'Tax Invoice',
  },
  {
    transactionDateTime: '14 May 2024 & 3:32pm',
    patientId: '12352',
    transactionId: 'xxx12345',
    service: 'Medication',
    totalAmount: '120000',
    gstAmount: '1200',
    paymentType: 'Cash',
    invoice: 'Tax Invoice',
  },
];

export { columns, users, paymentTypeOptions };
